---
# Pods in this deployment are responsible for queue ingest requests either
# from LTD Events consumers or from HTTP handlers.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ook-queue
  labels:
    app: ook-queue
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ook-queue
  template:
    metadata:
      labels:
        name: ook-queue
    spec:
      automountServiceAccountToken: false
      containers:
        - name: app
          imagePullPolicy: "Always"
          # Use images field in a Kustomization to regularly set/update image tag
          image: "lsstsqre/ook"
          ports:
            - containerPort: 8080
              name: app
          envFrom:
            - configMapRef:
                name: ook-queue
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - all
            readOnlyRootFilesystem: true
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
---
# Pods in this deployment are responsible for taking requests out of the
# ook.ingest Kafka topic and indexing the corresponding document into Algolia
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ook-ingest
  labels:
    app: ook-ingest
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ook-ingest
  template:
    metadata:
      labels:
        name: ook-ingest
    spec:
      automountServiceAccountToken: false
      containers:
        - name: app
          imagePullPolicy: "Always"
          # Use images field in a Kustomization to regularly set/update image tag
          image: "lsstsqre/ook"
          ports:
            - containerPort: 8080
              name: app
          envFrom:
            - configMapRef:
                name: ook-ingest
          env:
            - name: ALGOLIA_API_KEY
              valueFrom:
                secretKeyRef:
                  name: ook
                  key: algolia_api_key
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - all
            readOnlyRootFilesystem: true
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
