apiVersion: v1
kind: Service
metadata:
  name: ook
  labels:
    app: ook
spec:
  ports:
    - name: ook-http
      protocol: TCP
      port: 8080
      targetPort: app
  selector:
    # The HTTP ingess always goes to the ook-queue "frontend" deployment
    name: ook-queue
