"""Domain for external link checking."""

from ._engine import (
    accepts_contribution,
    canonicalize_url,
    contributed_outcome,
    evaluate_outcome,
    is_supported_url,
    normalize_origin_base_url,
)
from ._models import (
    AcceptedContribution,
    CheckedUrlReport,
    CheckResult,
    CheckRunStatus,
    CheckUrlStatus,
    ContributedResult,
    ContributionProvenance,
    ContributionProvider,
    ContributionRejectionReason,
    ContributionReport,
    LinkCheckOutcome,
    LinkCheckReport,
    LinkContribution,
    LinkState,
    LinkStatus,
    OriginLink,
    OriginPage,
    RejectedContribution,
    ResultSource,
    RetryLadderConfig,
    SubmittedUrl,
    UrlOccurrence,
    UrlRecord,
)

__all__ = [
    "AcceptedContribution",
    "CheckResult",
    "CheckRunStatus",
    "CheckUrlStatus",
    "CheckedUrlReport",
    "ContributedResult",
    "ContributionProvenance",
    "ContributionProvider",
    "ContributionRejectionReason",
    "ContributionReport",
    "LinkCheckOutcome",
    "LinkCheckReport",
    "LinkContribution",
    "LinkState",
    "LinkStatus",
    "OriginLink",
    "OriginPage",
    "RejectedContribution",
    "ResultSource",
    "RetryLadderConfig",
    "SubmittedUrl",
    "UrlOccurrence",
    "UrlRecord",
    "accepts_contribution",
    "canonicalize_url",
    "contributed_outcome",
    "evaluate_outcome",
    "is_supported_url",
    "normalize_origin_base_url",
]
