"""Add author_alias table

Revision ID: 34ea7479b953
Revises: 8e529b9177a0
Create Date: 2026-06-10 19:08:15.259400+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "34ea7479b953"
down_revision: str | None = "8e529b9177a0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "author_alias",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("internal_id", sa.UnicodeText(), nullable=False),
        sa.Column("author_id", sa.BigInteger(), nullable=False),
        sa.Column("date_updated", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_id"], ["author.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_author_alias_author_id"),
        "author_alias",
        ["author_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_author_alias_internal_id"),
        "author_alias",
        ["internal_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_author_alias_internal_id"), table_name="author_alias"
    )
    op.drop_index(op.f("ix_author_alias_author_id"), table_name="author_alias")
    op.drop_table("author_alias")
    # ### end Alembic commands ###
