"""Add intersphinx inventory table

Revision ID: c2a2c14c0e60
Revises: 818fdc36974d
Create Date: 2026-07-09 21:15:57.408740+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c2a2c14c0e60"
down_revision: str | None = "818fdc36974d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "intersphinx_inventory",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("url", sa.UnicodeText(), nullable=False),
        sa.Column("content", sa.LargeBinary(), nullable=True),
        sa.Column("content_type", sa.UnicodeText(), nullable=True),
        sa.Column("etag", sa.UnicodeText(), nullable=True),
        sa.Column("last_modified", sa.UnicodeText(), nullable=True),
        sa.Column("date_fetched", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "date_requested", sa.DateTime(timezone=True), nullable=False
        ),
        sa.Column("last_fetch_status", sa.UnicodeText(), nullable=True),
        sa.Column("last_fetch_error", sa.UnicodeText(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_intersphinx_inventory_date_fetched"),
        "intersphinx_inventory",
        ["date_fetched"],
        unique=False,
    )
    op.create_index(
        op.f("ix_intersphinx_inventory_date_requested"),
        "intersphinx_inventory",
        ["date_requested"],
        unique=False,
    )
    op.create_index(
        op.f("ix_intersphinx_inventory_url"),
        "intersphinx_inventory",
        ["url"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_intersphinx_inventory_url"),
        table_name="intersphinx_inventory",
    )
    op.drop_index(
        op.f("ix_intersphinx_inventory_date_requested"),
        table_name="intersphinx_inventory",
    )
    op.drop_index(
        op.f("ix_intersphinx_inventory_date_fetched"),
        table_name="intersphinx_inventory",
    )
    op.drop_table("intersphinx_inventory")
    # ### end Alembic commands ###
