"""Replace dead resource relation constraint with partial unique indexes

Revision ID: 3b66bd60b53f
Revises: cf936213314d
Create Date: 2026-07-08 20:30:37.833472+00:00

The whole-row ``uq_resource_relation`` unique constraint (PRD ook#238, issue
1.2) was ineffective: because exactly one of ``related_resource_id`` /
``related_external_ref_id`` is always NULL, PostgreSQL's default NULLS DISTINCT
semantics treated every row as distinct, so duplicate relation edges were never
rejected. It is replaced by two partial unique indexes, one per edge kind, each
scoped with a ``WHERE ... IS NOT NULL`` predicate that excludes the null side.

This migration also adds the supporting indexes that were missing (PRD ook#238,
issue 3.2): ``related_resource_id``, ``related_external_ref_id``, the composite
``(source_resource_id, relation_type)`` on ``resource_relation``, and
``author_id`` on ``contributor``.
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3b66bd60b53f"
down_revision: str | None = "cf936213314d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "idx_contributor_author", "contributor", ["author_id"], unique=False
    )
    op.drop_constraint(
        op.f("uq_resource_relation"), "resource_relation", type_="unique"
    )
    op.create_index(
        "idx_resource_relation_related_external_ref",
        "resource_relation",
        ["related_external_ref_id"],
        unique=False,
    )
    op.create_index(
        "idx_resource_relation_related_resource",
        "resource_relation",
        ["related_resource_id"],
        unique=False,
    )
    op.create_index(
        "idx_resource_relation_source_type",
        "resource_relation",
        ["source_resource_id", "relation_type"],
        unique=False,
    )
    op.create_index(
        "uq_resource_relation_external",
        "resource_relation",
        ["source_resource_id", "related_external_ref_id", "relation_type"],
        unique=True,
        postgresql_where=sa.text("related_external_ref_id IS NOT NULL"),
    )
    op.create_index(
        "uq_resource_relation_internal",
        "resource_relation",
        ["source_resource_id", "related_resource_id", "relation_type"],
        unique=True,
        postgresql_where=sa.text("related_resource_id IS NOT NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_resource_relation_internal",
        table_name="resource_relation",
        postgresql_where=sa.text("related_resource_id IS NOT NULL"),
    )
    op.drop_index(
        "uq_resource_relation_external",
        table_name="resource_relation",
        postgresql_where=sa.text("related_external_ref_id IS NOT NULL"),
    )
    op.drop_index(
        "idx_resource_relation_source_type", table_name="resource_relation"
    )
    op.drop_index(
        "idx_resource_relation_related_resource",
        table_name="resource_relation",
    )
    op.drop_index(
        "idx_resource_relation_related_external_ref",
        table_name="resource_relation",
    )
    op.create_unique_constraint(
        op.f("uq_resource_relation"),
        "resource_relation",
        [
            "source_resource_id",
            "related_resource_id",
            "related_external_ref_id",
            "relation_type",
        ],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_index("idx_contributor_author", table_name="contributor")
    # ### end Alembic commands ###
