"""Add external_reference url index and dedup key constraint

Revision ID: 20144e072aa7
Revises: 3b66bd60b53f
Create Date: 2026-07-08 20:48:54.283338+00:00

The ``_upsert_external_reference`` upsert path (PRD ook#238, issue 1.3)
resolves DOI-less references with ``ON CONFLICT (url)``, but no unique index
backed the ``url`` column, so that path raised ``ProgrammingError``. This adds
a partial unique index scoped with ``WHERE url IS NOT NULL`` so NULL URLs
(references keyed only by DOI/arXiv/etc.) stay distinct.

It also adds a check constraint requiring at least one dedup key (DOI, arXiv
ID, ISBN, ISSN, bibcode, or URL) so keyless references, which no ``ON
CONFLICT`` target can ever dedup, cannot accumulate as duplicates. The check
constraint is added manually because Alembic autogenerate does not detect
CHECK constraints.
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "20144e072aa7"
down_revision: str | None = "3b66bd60b53f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "uq_external_reference_url",
        "external_reference",
        ["url"],
        unique=True,
        postgresql_where=sa.text("url IS NOT NULL"),
    )
    # ### end Alembic commands ###
    op.create_check_constraint(
        "chk_external_reference_has_key",
        "external_reference",
        "doi IS NOT NULL OR arxiv_id IS NOT NULL OR isbn IS NOT NULL "
        "OR issn IS NOT NULL OR ads_bibcode IS NOT NULL OR url IS NOT NULL",
    )


def downgrade() -> None:
    op.drop_constraint(
        "chk_external_reference_has_key",
        "external_reference",
        type_="check",
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_external_reference_url",
        table_name="external_reference",
        postgresql_where=sa.text("url IS NOT NULL"),
    )
    # ### end Alembic commands ###
