"""Add linkcheck tables

Revision ID: c1ddff6dff7a
Revises: 34ea7479b953
Create Date: 2026-07-06 15:06:28.665068+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c1ddff6dff7a"
down_revision: str | None = "34ea7479b953"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "checked_url",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("url", sa.UnicodeText(), nullable=False),
        sa.Column("status", sa.UnicodeText(), nullable=True),
        sa.Column("status_code", sa.Integer(), nullable=True),
        sa.Column("redirect_url", sa.UnicodeText(), nullable=True),
        sa.Column("redirect_status_code", sa.Integer(), nullable=True),
        sa.Column("error", sa.UnicodeText(), nullable=True),
        sa.Column(
            "last_checked_at", sa.DateTime(timezone=True), nullable=True
        ),
        sa.Column("last_ok_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failing_since", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failure_count", sa.Integer(), nullable=False),
        sa.Column("next_check_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("check_method", sa.UnicodeText(), nullable=False),
        sa.Column("date_created", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_checked_url_last_checked_at"),
        "checked_url",
        ["last_checked_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_checked_url_next_check_at"),
        "checked_url",
        ["next_check_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_checked_url_status"), "checked_url", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_checked_url_url"), "checked_url", ["url"], unique=True
    )
    op.create_table(
        "linkcheck_check",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("ltd_slug", sa.UnicodeText(), nullable=False),
        sa.Column("default_branch", sa.Boolean(), nullable=False),
        sa.Column("status", sa.UnicodeText(), nullable=False),
        sa.Column("date_created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("date_completed", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_linkcheck_check_date_created"),
        "linkcheck_check",
        ["date_created"],
        unique=False,
    )
    op.create_index(
        op.f("ix_linkcheck_check_ltd_slug"),
        "linkcheck_check",
        ["ltd_slug"],
        unique=False,
    )
    op.create_table(
        "linkcheck_check_url",
        sa.Column("check_id", sa.BigInteger(), nullable=False),
        sa.Column("checked_url_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["check_id"], ["linkcheck_check.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["checked_url_id"], ["checked_url.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("check_id", "checked_url_id"),
    )
    op.create_index(
        op.f("ix_linkcheck_check_url_checked_url_id"),
        "linkcheck_check_url",
        ["checked_url_id"],
        unique=False,
    )
    op.create_table(
        "url_occurrence",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("ltd_slug", sa.UnicodeText(), nullable=False),
        sa.Column("path", sa.UnicodeText(), nullable=False),
        sa.Column("checked_url_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["checked_url_id"], ["checked_url.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "ltd_slug", "path", "checked_url_id", name="uq_url_occurrence"
        ),
    )
    op.create_index(
        op.f("ix_url_occurrence_checked_url_id"),
        "url_occurrence",
        ["checked_url_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_url_occurrence_ltd_slug"),
        "url_occurrence",
        ["ltd_slug"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_url_occurrence_ltd_slug"), table_name="url_occurrence"
    )
    op.drop_index(
        op.f("ix_url_occurrence_checked_url_id"), table_name="url_occurrence"
    )
    op.drop_table("url_occurrence")
    op.drop_index(
        op.f("ix_linkcheck_check_url_checked_url_id"),
        table_name="linkcheck_check_url",
    )
    op.drop_table("linkcheck_check_url")
    op.drop_index(
        op.f("ix_linkcheck_check_ltd_slug"), table_name="linkcheck_check"
    )
    op.drop_index(
        op.f("ix_linkcheck_check_date_created"), table_name="linkcheck_check"
    )
    op.drop_table("linkcheck_check")
    op.drop_index(op.f("ix_checked_url_url"), table_name="checked_url")
    op.drop_index(op.f("ix_checked_url_status"), table_name="checked_url")
    op.drop_index(
        op.f("ix_checked_url_next_check_at"), table_name="checked_url"
    )
    op.drop_index(
        op.f("ix_checked_url_last_checked_at"), table_name="checked_url"
    )
    op.drop_table("checked_url")
    # ### end Alembic commands ###
