"""Add origin_paths to linkcheck_check_url

Revision ID: e3224f7fa2cb
Revises: 97e2df2ad883
Create Date: 2026-07-07 20:14:25.536129+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e3224f7fa2cb"
down_revision: str | None = "97e2df2ad883"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "linkcheck_check_url",
        sa.Column(
            "origin_paths",
            sa.ARRAY(sa.UnicodeText()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("linkcheck_check_url", "origin_paths")
    # ### end Alembic commands ###
