"""Add intersphinx entity, source, and link tables

Revision ID: ec0c04ddd611
Revises: f43554a10acb
Create Date: 2026-09-02 18:40:41.990681+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ec0c04ddd611"
down_revision: str | None = "f43554a10acb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "intersphinx_entity",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("sphinx_domain", sa.UnicodeText(), nullable=False),
        sa.Column("name", sa.UnicodeText(), nullable=False),
        sa.Column("role", sa.UnicodeText(), nullable=False),
        sa.Column("display_name", sa.UnicodeText(), nullable=False),
        sa.Column("parent_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "extras", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"], ["intersphinx_entity.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "sphinx_domain", "name", name="uq_intersphinx_entity_name"
        ),
    )
    op.create_index(
        op.f("ix_intersphinx_entity_parent_id"),
        "intersphinx_entity",
        ["parent_id"],
        unique=False,
    )
    op.create_table(
        "intersphinx_source",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("url", sa.UnicodeText(), nullable=False),
        sa.Column("title", sa.UnicodeText(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("date_ingested", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_status", sa.UnicodeText(), nullable=True),
        sa.Column("last_error", sa.UnicodeText(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_intersphinx_source_url"),
        "intersphinx_source",
        ["url"],
        unique=True,
    )
    op.create_table(
        "links_intersphinx",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("entity_id", sa.BigInteger(), nullable=False),
        sa.Column("source_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["entity_id"], ["intersphinx_entity.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["id"], ["link.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["source_id"], ["intersphinx_source.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_links_intersphinx_entity_id"),
        "links_intersphinx",
        ["entity_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_links_intersphinx_source_id"),
        "links_intersphinx",
        ["source_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_links_intersphinx_source_id"), table_name="links_intersphinx"
    )
    op.drop_index(
        op.f("ix_links_intersphinx_entity_id"), table_name="links_intersphinx"
    )
    op.drop_table("links_intersphinx")
    op.drop_index(
        op.f("ix_intersphinx_source_url"), table_name="intersphinx_source"
    )
    op.drop_table("intersphinx_source")
    op.drop_index(
        op.f("ix_intersphinx_entity_parent_id"),
        table_name="intersphinx_entity",
    )
    op.drop_table("intersphinx_entity")
    # ### end Alembic commands ###
