"""Add consecutive_blocked_count to checked_url

Revision ID: 818fdc36974d
Revises: 20144e072aa7
Create Date: 2026-07-10 20:34:16.073658+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "818fdc36974d"
down_revision: str | None = "20144e072aa7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Add the column NOT NULL with a temporary server default so existing
    # rows backfill to zero, then drop the default so the column matches
    # the ORM model (which supplies the value on every insert, like
    # failure_count).
    op.add_column(
        "checked_url",
        sa.Column(
            "consecutive_blocked_count",
            sa.Integer(),
            nullable=False,
            server_default="0",
        ),
    )
    op.alter_column(
        "checked_url", "consecutive_blocked_count", server_default=None
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("checked_url", "consecutive_blocked_count")
    # ### end Alembic commands ###
