name: CI

env:
  UV_VERSION: "0.11.7"

"on":
  merge_group: {}
  pull_request: {}
  push:
    branches-ignore:
      # These should always correspond to pull requests, so ignore them for
      # the push trigger and let them be triggered by the pull_request
      # trigger, avoiding running the workflow twice.  This is a minor
      # optimization so there's no need to ensure this is comprehensive.
      - "dependabot/**"
      - "gh-readonly-queue/**"
      - "renovate/**"
      - "t/**"
      - "tickets/**"
      - "u/**"
  release:
    types: [published]

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: ${{ env.UV_VERSION }}

      - name: Run pre-commit
        run: uv run --group=lint pre-commit run --all-files

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: ${{ env.UV_VERSION }}

      - name: Run nox
        run: uv run --group=nox nox -s typing test-coverage

  docs:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v6
        with:
          # Ensure the documentation gets the right version.
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: ${{ env.UV_VERSION }}

      - name: Update package lists
        run: sudo apt-get update

      - name: Install extra packages
        run: sudo apt install -y graphviz

      - name: Run nox
        run: uv run --group=nox nox -s docs

      # Only attempt documentation uploads for long-lived branches, tagged
      # releases, and pull requests from ticket branches.  This avoids version
      # clutter in the docs and failures when a PR doesn't have access to
      # secrets.
      - name: Upload to LSST the Docs
        uses: lsst-sqre/ltd-upload@v1
        with:
          project: ook
          dir: "docs/_build/html"
          username: ${{ secrets.LTD_USERNAME }}
          password: ${{ secrets.LTD_PASSWORD }}
        if: >
          github.event_name != 'merge_group'
          && (github.event_name != 'pull_request'
              || (startsWith(github.head_ref, 'tickets/')
                  || startsWith(github.head_ref, 't/')))

  build:
    needs: [test]
    secrets: inherit
    uses: lsst-sqre/multiplatform-build-and-push/.github/workflows/build.yaml@v4
    with:
      images: ghcr.io/${{ github.repository }}

    # Only do Docker builds of tagged releases and pull requests from ticket
    # branches.  This will still trigger on pull requests from untrusted
    # repositories whose branch names match our tickets/* branch convention,
    # but in this case the build will fail with an error since the secret
    # won't be set.
    # Only do Docker builds of releases and pull requests from ticket
    # branches. This will still trigger on pull requests from untrusted
    # repositories whose branch names match our tickets/* branch convention,
    # but in this case the build will fail with an error since the secret
    # won't be set.
    if: >
      (github.event_name == 'release' && github.event.action == 'published')
      || (github.event_name != 'merge_group'
          && (startsWith(github.head_ref, 'tickets/')
              || startsWith(github.head_ref, 't/')))
