# This is a separate run of the Python test suite that runs from a schedule,
# doesn't cache the tox environment, and updates pinned dependencies first.
# The purpose is to test compatibility with the latest versions of
# dependencies.

name: Periodic CI

env:
  PYTHON_VERSION: "3.12"

"on":
  schedule:
    - cron: "0 12 * * 1"
  workflow_dispatch: {}

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - name: Update dependencies
        uses: lsst-sqre/run-nox@v1
        with:
          nox-sessions: "update-deps"
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Run nox
        uses: lsst-sqre/run-nox@v1
        with:
          nox-sessions: "typing test docs"
          python-version: ${{ env.PYTHON_VERSION }}
          use-cache: false
          nox-package: "nox[uv] testcontainers[kafka]"

      - name: Report status
        if: always()
        uses: ravsamhq/notify-slack-action@v2
        with:
          status: ${{ job.status }}
          notify_when: "failure"
          notification_title: "Periodic test for {repo} failed"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_ALERT_WEBHOOK }}
